name: "ethiopian_medical_data"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "ethiopian_medical_data"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ethiopian_medical_data:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

# Variables
vars:
  # Define default date range for incremental models
  start_date: "2024-01-01"

# Seeds configuration
seeds:
  ethiopian_medical_data:
    +schema: seeds

# Tests configuration
tests:
  ethiopian_medical_data:
    +store_failures: true
